### ISSUE TITLE
Linking fails in Xcode 12 beta 2 on Archive even after PR #392 is accepted

### ISSUE THREAD

**Issue by illabo** [marmelroy/PhoneNumberKit#393]
Archiving project with Xcode 12 beta 2 fails with the following linker error:
```
Undefined symbols for architecture armv7:
  "type metadata for Swift._StringObject.Variant", referenced from:
      outlined init with take of Swift._StringObject.Variant in CountryCodePickerViewController.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
This error expected to be resolved with #392, however it still persists.
Pod added from master: ` pod 'PhoneNumberKit', :git => 'https://github.com/marmelroy/PhoneNumberKit.git'`, build folder is cleaned beforehand. Debug builds are successful and runnable.

**Comment by illabo** [comment]
Have to explicitly remove arm7 from target build settings and Pods project.
