### ISSUE TITLE
V3.7.6 Compilation error : value of optional type 'NSRegularExpression?' must be unwrapped to refer to member 'firstMatch' of wrapped base type 'NSRegularExpression'

### ISSUE THREAD

**Issue by NishanthMurugan** [marmelroy/PhoneNumberKit#728]
App failed to compile with latest version 3.7.6 with following error

PhoneNumberKit/PartialFormatter.swift:205:22: value of optional type 'NSRegularExpression?' must be unwrapped to refer to member 'firstMatch' of wrapped base type 'NSRegularExpression'

<img width="486" alt="Screenshot 2023-12-07 at 7 50 35 PM" src="https://github.com/marmelroy/PhoneNumberKit/assets/30654850/9edcd733-fdb3-4ba9-a6c8-e64ad6c9cbbd">

Please help to fix it.

**Comment by NishanthMurugan** [comment]
Changed swift version to 5
